version: '2'
services:
  storage:
    image: debian:jessie
    entrypoint: /bin/true
    volumes:
      - ./:/var/www/html
    network_mode: "bridge"

  phpfpm:
    build: ./docker/development/php
    image: yuv/dev-phpfpm
    links:
     - mysql:mysql
     - redis:redis
    expose:
     - "8080"
    volumes:
     - ./docker/development/php/php.ini:/usr/local/etc/php/php.ini
    volumes_from:
     - storage
    environment:
      REDIS_PORT: 6379
    network_mode: "bridge"

  nginx:
    build: ./docker/development/nginx
    links:
      - phpfpm:phpfpm
    ports:
     - "8080:80"
    volumes:
     - ./docker/development/nginx/nginx.conf:/etc/nginx/nginx.conf
    volumes_from:
     - storage
    environment:
      VIRTUAL_HOST: nhtsa.local
    network_mode: "bridge"

  mysql:
    build: ./docker/development/mysql
    ports:
      - "33068:3306"
    environment:
      MYSQL_ROOT_PASSWORD: nhtsa
      MYSQL_DATABASE: nhtsa
      MYSQL_USER: nhtsa
      MYSQL_PASSWORD: nhtsa
    network_mode: "bridge"

  redis:
    build: ./docker/development/redis
    ports:
      - "63798:6379"
    volumes:
      - ./storage/redis:/data
      - ./docker/development/redis/redis.conf:/usr/local/etc/redis/redis.conf
    network_mode: "bridge"
    entrypoint:
      - redis-server
      - "--appendonly yes"
